// Code generated by sqlc. DO NOT EDIT.
// Versions:
//   sqlc v1.26.0
//
// To regenerate: sqlc generate

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DBTX is the minimal interface that both *pgx.Conn and *pgxpool.Pool satisfy.
// Accepting an interface (rather than a concrete type) keeps Queries decoupled
// from how the connection was created, and makes it trivial to pass a pgx.Tx
// during a database transaction.
type DBTX interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

// New returns a Queries object backed by db.
// Pass either a *pgxpool.Pool (normal usage) or a pgx.Tx (transactional usage).
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// WithTx returns a copy of Queries scoped to the given transaction.
// Use this when you need to execute multiple statements atomically:
//
//	tx, _ := pool.Begin(ctx)
//	qtx := queries.WithTx(tx)
//	qtx.CreateUser(ctx, ...)
//	tx.Commit(ctx)
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}

// Queries is the central data-access struct.
// Every SQL query in db/queries/ becomes a method on this type.
type Queries struct {
	db DBTX
}
