// Code generated by sqlc. DO NOT EDIT.
// Versions:
//   sqlc v1.26.0

package db

import "time"

// User mirrors the `users` table exactly.
// The json tags are emitted because emit_json_tags: true is set in sqlc.yaml,
// which lets us marshal/unmarshal this struct directly in HTTP handlers.
type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
