// Code generated by sqlc. DO NOT EDIT.
// Versions:
//   sqlc v1.26.0
// Source: user.sql

package db

import (
	"context"
)

// ---------------------------------------------------------------------------
// GetUser
// ---------------------------------------------------------------------------

const getUserQuery = `-- name: GetUser :one
SELECT id, name, email, created_at FROM users
WHERE id = $1
LIMIT 1`

// GetUser fetches a single user by primary key.
// Returns pgx.ErrNoRows if no row is found — callers should check for this
// explicitly so they can return a 404 rather than a 500.
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserQuery, id)

	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Email, &u.CreatedAt)
	return u, err
}

// ---------------------------------------------------------------------------
// ListUsers
// ---------------------------------------------------------------------------

const listUsersQuery = `-- name: ListUsers :many
SELECT id, name, email, created_at FROM users
ORDER BY created_at DESC`

// ListUsers returns every user ordered newest-first.
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var users []User
	for rows.Next() {
		var u User
		if err := rows.Scan(&u.ID, &u.Name, &u.Email, &u.CreatedAt); err != nil {
			return nil, err
		}
		users = append(users, u)
	}

	// rows.Err() captures any error that occurred during iteration —
	// always check it after the loop.
	return users, rows.Err()
}

// ---------------------------------------------------------------------------
// CreateUser
// ---------------------------------------------------------------------------

// CreateUserParams holds the caller-supplied fields for a new user.
// sqlc generates one *Params struct per INSERT/UPDATE query.
type CreateUserParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

const createUserQuery = `-- name: CreateUser :one
INSERT INTO users (name, email)
VALUES ($1, $2)
RETURNING id, name, email, created_at`

// CreateUser inserts a new user and returns the fully populated row
// (including the database-assigned id and created_at).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserQuery, arg.Name, arg.Email)

	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Email, &u.CreatedAt)
	return u, err
}

// ---------------------------------------------------------------------------
// DeleteUser
// ---------------------------------------------------------------------------

const deleteUserQuery = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1`

// DeleteUser removes a user by ID. It is not an error if no row is deleted;
// handlers that need to distinguish "not found" should call GetUser first.
func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUserQuery, id)
	return err
}
